const getBaseUrl = require('../../../utils/getBaseUrl');
const {
  AccountViewAPI,
  AffiliateAPI,
  AttachmentsAPI,
  AuditAPI,
  Auth2API,
  CallbackAPI,
  Click2CallAPI,
  CoperatoSmsAPI,
  EmailAPI,
  OperatorConfigAPI,
  HierarchyAPI,
  HierarchyUpdaterAPI,
  LeadAPI,
  LeadUpdaterAPI,
  NoteAPI,
  NotificationCenterAPI,
  OperatorAPI,
  PaymentAPI,
  ProfileAPI,
  ProfileViewAPI,
  TradingAccountAPI,
  TradingActivityAPI,
  RuleProfileAPI,
  ReferralAPI,
  DistributionRuleAPI,
  AnalyticsAPI,
  TradingEngineAPI,
  BrandConfigAPI,
  LiquidityProviderAPI,
} = require('../dataSources');

module.exports = () => ({
  AccountViewAPI: new AccountViewAPI({ baseUrl: getBaseUrl('accountview') }),
  AffiliateAPI: new AffiliateAPI({ baseUrl: getBaseUrl('affiliate') }),
  AttachmentsAPI: new AttachmentsAPI({ baseUrl: getBaseUrl('attachments') }),
  AuditAPI: new AuditAPI({ baseUrl: getBaseUrl('audit') }),
  Auth2API: new Auth2API({ baseUrl: getBaseUrl('auth2') }),
  CallbackAPI: new CallbackAPI({ baseUrl: getBaseUrl('callback') }),
  Click2CallAPI: new Click2CallAPI({ baseUrl: getBaseUrl('click-to-call') }),
  CoperatoSmsAPI: new CoperatoSmsAPI({ baseUrl: '' }),
  EmailAPI: new EmailAPI({ baseUrl: getBaseUrl('email') }),
  OperatorConfigAPI: new OperatorConfigAPI({ baseUrl: getBaseUrl('operator-config') }),
  HierarchyAPI: new HierarchyAPI({ baseUrl: getBaseUrl('hierarchy') }),
  HierarchyUpdaterAPI: new HierarchyUpdaterAPI({ baseUrl: getBaseUrl('hierarchy-updater') }),
  LeadAPI: new LeadAPI({ baseUrl: getBaseUrl('lead') }),
  LeadUpdaterAPI: new LeadUpdaterAPI({ baseUrl: getBaseUrl('lead-updater') }),
  NoteAPI: new NoteAPI({ baseUrl: getBaseUrl('note') }),
  NotificationCenterAPI: new NotificationCenterAPI({ baseUrl: getBaseUrl('notification') }),
  OperatorAPI: new OperatorAPI({ baseUrl: getBaseUrl('operator') }),
  PaymentAPI: new PaymentAPI({ baseUrl: getBaseUrl('payment') }),
  ProfileAPI: new ProfileAPI({ baseUrl: getBaseUrl('profile') }),
  ProfileViewAPI: new ProfileViewAPI({ baseUrl: getBaseUrl('profileview') }),
  TradingAccountAPI: new TradingAccountAPI({ baseUrl: getBaseUrl('trading-account') }),
  TradingActivityAPI: new TradingActivityAPI({ baseUrl: getBaseUrl('trading-activity') }),
  RuleProfileAPI: new RuleProfileAPI({ baseUrl: getBaseUrl('rules-profile') }),
  ReferralAPI: new ReferralAPI({ baseUrl: getBaseUrl('referral') }),
  DistributionRuleAPI: new DistributionRuleAPI({ baseUrl: getBaseUrl('clients-distributor') }),
  AnalyticsAPI: new AnalyticsAPI({ baseUrl: getBaseUrl('analytics-api') }),
  TradingEngineAPI: new TradingEngineAPI({ baseUrl: getBaseUrl('we-trading') }),
  BrandConfigAPI: new BrandConfigAPI({ baseUrl: getBaseUrl('brand-config-service') }),
  LiquidityProviderAPI: new LiquidityProviderAPI({ baseUrl: getBaseUrl('liquidity-provider-adapter') }),
});
