all-roles: &all-roles
  - EXECUTIVE
  - TEAM_LEADER
  - MANAGER
  - HEAD_OF_DEPARTMENT

operators: &all
  - department: ADMINISTRATION
    roles:
      - ADMINISTRATION
  - department: RFP
    roles:
      - HEAD_OF_DEPARTMENT
  - department: CS
    roles: *all-roles
  - department: SALES
    roles: *all-roles
  - department: RETENTION
    roles: *all-roles

permissions:
  actions:
    - action: "profile.field.phone"
      authorities: *all
    - action: "profile.field.additionalPhone"
      authorities: *all
    - action: "profile.field.email"
      authorities: *all
    - action: "profile.field.additionalEmail"
      authorities: *all
    - action: "profile.affiliate.field.uuid"
      authorities: *all
    - action: "profile.affiliate.field.campaignId"
      authorities: *all
    - action: "profile.affiliate.field.referral"
      authorities: *all
    - action: "profile.affiliate.field.source"
      authorities: *all
    - action: "profile.affiliate.field.sms"
      authorities: *all
    - action: "profile.referrer.field.uuid"
      authorities: *all
    - action: "profile.referrer.field.fullName"
      authorities: *all
    - action: "lead.field.phone"
      authorities: *all
    - action: "lead.field.mobile"
      authorities: *all
    - action: "lead.field.email"
      authorities: *all
    - action: "payment.field.manual-methods.values.BONUS"
      authorities: *all
    - action: "payment.field.manual-methods.values.CHARGEBACK"
      authorities: *all
    - action: "payment.field.manual-methods.values.CREDIT_CARD"
      authorities: *all
    - action: "payment.field.manual-methods.values.ELECTRONIC"
      authorities: *all
    - action: "payment.field.manual-methods.values.EXTERNAL"
      authorities: *all
    - action: "payment.field.manual-methods.values.INTERNAL_TRANSFER"
      authorities: *all
    - action: "payment.field.manual-methods.values.MIGRATION"
      authorities: *all
    - action: "payment.field.manual-methods.values.PAYRETAILERS"
      authorities: *all
    - action: "payment.field.manual-methods.values.RECALL"
      authorities: *all
    - action: "payment.field.manual-methods.values.SYSTEM"
      authorities: *all
    - action: "payment.field.manual-methods.values.WIRE"
      authorities: *all
