all-roles: &all-roles
  - EXECUTIVE
  - TEAM_LEADER
  - MANAGER
  - HEAD_OF_DEPARTMENT

complete-department-roles: &complete-department-roles
  - SHIFT_SALES
  - SHIFT_RETENTION
  - SALES_MANAGER
  - SALES_LEAD_MANAGER

operators: &all
  - department: ADMINISTRATION
    roles:
      - ADMINISTRATION
  - department: RFP
    roles:
      - HEAD_OF_DEPARTMENT
  - department: CS
    roles: *all-roles
  - department: SALES
    roles: *all-roles
  - department: RETENTION
    roles: *all-roles
  - department: COMPLETE
    roles: *complete-department-roles

operators-with-payment-department: &all-with-payment-department
  - department: ADMINISTRATION
    roles:
      - ADMINISTRATION
  - department: RFP
    roles:
      - HEAD_OF_DEPARTMENT
  - department: CS
    roles: *all-roles
  - department: SALES
    roles: *all-roles
  - department: RETENTION
    roles: *all-roles
  - department: PAYMENT
    roles: *all-roles
  - department: COMPLETE
    roles: *complete-department-roles

sidebar-authorities: &sidebar-authorities
  - department: ADMINISTRATION
    roles:
      - ADMINISTRATION
      - CLIENT_DISTRIBUTION
  - department: AFFILIATE
    roles:
      - AFFILIATE
  - department: AFFILIATE_MANAGER
    roles: *all-roles
  - department: BI
    roles:
      - BI
  - department: COMPLETE
    roles: *complete-department-roles
  - department: COMPLIANCE
    roles:
      - COMPLIANCE
      - COMPLIANCE_MANAGER
  - department: CS
    roles: *all-roles
  - department: DEALING
    roles: *all-roles
  - department: DIDLOGIC
    roles:
      - DIDLOGIC
  - department: FINANCE
    roles: *all-roles
  - department: IB
    roles:
      - AGENT
  - department: MARKETING
    roles:
      - MARKETING
  - department: PAYMENT
    roles: *all-roles
  - department: RBAC
    roles:
      - RBAC
  - department: RETENTION
    roles: *all-roles
  - department: RFP
    roles: *all-roles
  - department: SALES
    roles: *all-roles

permissions:
  actions:
    - action: "profile.field.phone"
      authorities:
        - department: ADMINISTRATION
          roles:
            - ADMINISTRATION
        - department: RFP
          roles:
            - HEAD_OF_DEPARTMENT
        - department: CS
          roles: *all-roles
        - department: SALES
          roles: *all-roles
        - department: RETENTION
          roles: *all-roles
        - department: PAYMENT
          roles:
            - TEAM_LEADER
            - HEAD_OF_DEPARTMENT
        - department: COMPLETE
          roles: *complete-department-roles
    - action: "profile.field.additionalPhone"
      authorities:
        - department: ADMINISTRATION
          roles:
            - ADMINISTRATION
        - department: RFP
          roles:
            - HEAD_OF_DEPARTMENT
        - department: CS
          roles: *all-roles
        - department: SALES
          roles: *all-roles
        - department: RETENTION
          roles: *all-roles
        - department: PAYMENT
          roles:
            - TEAM_LEADER
            - HEAD_OF_DEPARTMENT
        - department: COMPLETE
          roles: *complete-department-roles
    - action: "profile.field.email"
      authorities: *all-with-payment-department
    - action: "profile.field.additionalEmail"
      authorities: *all-with-payment-department
    - action: "profile.field.balance"
      authorities: *all-with-payment-department
    - action: "profile.affiliate.field.uuid"
      authorities:
        - department: ADMINISTRATION
          roles:
            - ADMINISTRATION
        - department: RFP
          roles:
            - HEAD_OF_DEPARTMENT
        - department: CS
          roles: *all-roles
        - department: SALES
          roles: *all-roles
        - department: RETENTION
          roles: *all-roles
        - department: COMPLIANCE
          roles:
            - COMPLIANCE_MANAGER
        - department: COMPLETE
          roles: *complete-department-roles
    - action: "profile.affiliate.field.campaignId"
      authorities: *all
    - action: "profile.affiliate.field.referral"
      authorities: *all
    - action: "profile.affiliate.field.source"
      authorities: *all-with-payment-department
    - action: "profile.field.convertedFromLeadUuid"
      authorities: *all
    - action: "profile.affiliate.field.sms"
      authorities: *all
    - action: "profile.referrer.field.uuid"
      authorities: *all
    - action: "profile.referrer.field.fullName"
      authorities: *all
    - action: "lead.field.phone"
      authorities: *all
    - action: "lead.field.mobile"
      authorities: *all
    - action: "lead.field.email"
      authorities: *all
    - action: "sidebar.clientsList"
      authorities: *sidebar-authorities
    - action: "sidebar.clientsKycDocuments"
      authorities: *sidebar-authorities
    - action: "sidebar.clientsTradingAccounts"
      authorities: *sidebar-authorities
    - action: "sidebar.clientsCallbacks"
      authorities: *sidebar-authorities
    - action: "sidebar.leadsList"
      authorities: *sidebar-authorities
    - action: "sidebar.leadsCallbacks"
      authorities: *sidebar-authorities
    - action: "sidebar.hierarchy"
      authorities: *sidebar-authorities
    - action: "sidebar.managmentOffices"
      authorities: *sidebar-authorities
    - action: "sidebar.managmentDesks"
      authorities: *sidebar-authorities
    - action: "sidebar.managmentTeams"
      authorities: *sidebar-authorities
    - action: "sidebar.managmentSalesRules"
      authorities: *sidebar-authorities
    - action: "sidebar.managmentOperators"
      authorities: *sidebar-authorities
    - action: "sidebar.managmentPartners"
      authorities: *sidebar-authorities
    - action: "sidebar.documents"
      authorities: *sidebar-authorities
    - action: "sidebar.payments"
      authorities: *sidebar-authorities
    - action: "sidebar.notifications"
      authorities: *sidebar-authorities
    - action: "sidebar.clientsDistibution"
      authorities: *sidebar-authorities
    - action: "sidebar.ipWhitelist"
      authorities: *sidebar-authorities
    - action: "sidebar.settingsEmailTemplates"
      authorities: *sidebar-authorities
    - action: "sidebar.settingsRbac"
      authorities: *sidebar-authorities
    - action: "sidebar.settingsAcquisitionStatuses"
      authorities: *sidebar-authorities
    - action: "sidebar.settingsFeatureToggles"
      authorities:
        - department: ADMINISTRATION
          roles:
            - ADMINISTRATION
    - action: "payment.field.manual-methods.values.BONUS"
      authorities: *all-with-payment-department
    - action: "payment.field.manual-methods.values.CHARGEBACK"
      authorities: *all-with-payment-department
    - action: "payment.field.manual-methods.values.CREDIT_CARD"
      authorities: *all-with-payment-department
    - action: "payment.field.manual-methods.values.ELECTRONIC"
      authorities: *all-with-payment-department
    - action: "payment.field.manual-methods.values.EXTERNAL"
      authorities: *all-with-payment-department
    - action: "payment.field.manual-methods.values.INTERNAL_TRANSFER"
      authorities: *all-with-payment-department
    - action: "payment.field.manual-methods.values.MIGRATION"
      authorities: *all-with-payment-department
    - action: "payment.field.manual-methods.values.PAYRETAILERS"
      authorities: *all-with-payment-department
    - action: "payment.field.manual-methods.values.RECALL"
      authorities: *all-with-payment-department
    - action: "payment.field.manual-methods.values.SYSTEM"
      authorities: *all-with-payment-department
    - action: "payment.field.manual-methods.values.WIRE"
      authorities: *all-with-payment-department
    - action: "payment.field.manual-methods.values.COMMISSION"
      authorities:
        - department: ADMINISTRATION
          roles:
            - ADMINISTRATION
        - department: CS
          roles:
            - MANAGER
    - action: "dashboard.getScreenerWidget"
      authorities:
        - department: ADMINISTRATION
          roles:
            - ADMINISTRATION
        - department: CS
          roles:
            - EXECUTIVE
            - HEAD_OF_DEPARTMENT
