all-roles: &all-roles
  - EXECUTIVE
  - TEAM_LEADER
  - MANAGER
  - HEAD_OF_DEPARTMENT

complete-department-roles: &complete-department-roles
  - SHIFT_SALES
  - SHIFT_RETENTION
  - SALES_MANAGER
  - SALES_LEAD_MANAGER

operators: &all
  - department: ADMINISTRATION
    roles:
      - ADMINISTRATION
  - department: RFP
    roles:
      - HEAD_OF_DEPARTMENT
  - department: CS
    roles: *all-roles
  - department: SALES
    roles: *all-roles
  - department: RETENTION
    roles: *all-roles
  - department: COMPLETE
    roles: *complete-department-roles

operators-with-payment-department: &all-with-payment-department
  - department: ADMINISTRATION
    roles:
      - ADMINISTRATION
  - department: RFP
    roles:
      - HEAD_OF_DEPARTMENT
  - department: CS
    roles: *all-roles
  - department: SALES
    roles: *all-roles
  - department: RETENTION
    roles: *all-roles
  - department: PAYMENT
    roles: *all-roles
  - department: COMPLETE
    roles: *complete-department-roles

permissions:
  actions:
    - action: "profile.field.phone"
      authorities:
        - department: ADMINISTRATION
          roles:
            - ADMINISTRATION
        - department: RFP
          roles:
            - HEAD_OF_DEPARTMENT
        - department: CS
          roles: *all-roles
        - department: SALES
          roles: *all-roles
        - department: RETENTION
          roles: *all-roles
        - department: PAYMENT
          roles:
            - TEAM_LEADER
            - HEAD_OF_DEPARTMENT
        - department: COMPLETE
          roles: *complete-department-roles
    - action: "profile.field.additionalPhone"
      authorities:
        - department: ADMINISTRATION
          roles:
            - ADMINISTRATION
        - department: RFP
          roles:
            - HEAD_OF_DEPARTMENT
        - department: CS
          roles: *all-roles
        - department: SALES
          roles: *all-roles
        - department: RETENTION
          roles: *all-roles
        - department: PAYMENT
          roles:
            - TEAM_LEADER
            - HEAD_OF_DEPARTMENT
        - department: COMPLETE
          roles: *complete-department-roles
    - action: "profile.field.email"
      authorities: *all-with-payment-department
    - action: "profile.field.additionalEmail"
      authorities: *all-with-payment-department
    - action: "profile.field.balance"
      authorities: *all-with-payment-department
    - action: "profile.affiliate.field.uuid"
      authorities:
        - department: ADMINISTRATION
          roles:
            - ADMINISTRATION
        - department: RFP
          roles:
            - HEAD_OF_DEPARTMENT
        - department: CS
          roles: *all-roles
        - department: SALES
          roles: *all-roles
        - department: RETENTION
          roles: *all-roles
        - department: COMPLIANCE
          roles:
            - COMPLIANCE_MANAGER
        - department: COMPLETE
          roles: *complete-department-roles
    - action: "profile.affiliate.field.campaignId"
      authorities: *all
    - action: "profile.affiliate.field.referral"
      authorities: *all
    - action: "profile.affiliate.field.source"
      authorities: *all-with-payment-department
    - action: "profile.affiliate.field.sms"
      authorities: *all
    - action: "profile.referrer.field.uuid"
      authorities: *all
    - action: "profile.referrer.field.fullName"
      authorities: *all
    - action: "lead.field.phone"
      authorities: *all
    - action: "lead.field.mobile"
      authorities: *all
    - action: "lead.field.email"
      authorities: *all
    - action: "payment.field.manual-methods.values.BONUS"
      authorities: *all-with-payment-department
    - action: "payment.field.manual-methods.values.CHARGEBACK"
      authorities: *all-with-payment-department
    - action: "payment.field.manual-methods.values.CREDIT_CARD"
      authorities: *all-with-payment-department
    - action: "payment.field.manual-methods.values.ELECTRONIC"
      authorities: *all-with-payment-department
    - action: "payment.field.manual-methods.values.EXTERNAL"
      authorities: *all-with-payment-department
    - action: "payment.field.manual-methods.values.INTERNAL_TRANSFER"
      authorities: *all-with-payment-department
    - action: "payment.field.manual-methods.values.MIGRATION"
      authorities: *all-with-payment-department
    - action: "payment.field.manual-methods.values.PAYRETAILERS"
      authorities: *all-with-payment-department
    - action: "payment.field.manual-methods.values.RECALL"
      authorities: *all-with-payment-department
    - action: "payment.field.manual-methods.values.SYSTEM"
      authorities: *all-with-payment-department
    - action: "payment.field.manual-methods.values.WIRE"
      authorities: *all-with-payment-department
    - action: "dashboard.getScreenerWidget"
      authorities: *all
