module.exports = {
  auth: require('./auth'),
  profile: require('./profile'),
  notes: require('./notes'),
  tradingActivities: require('./tradingActivities'),
  tradingAccount: require('./tradingAccount'),
  statistics: require('./statistics'),
  profiles: require('./profiles'),
  upload: require('./upload'),
  leads: require('./leads'),
  files: require('./files'),
  hierarchy: require('./hierarchy'),
  rules: require('./rules'),
  clients: require('./clients'),
  operators: require('./operators'),
  partners: require('./partners'),
  metabase: require('./metabase'),
};
