module.exports = {
  audit: require('./audit'),
  auth: require('./auth'),
  authorization: require('./authorization'),
  payment: require('./payment'),
  profile: require('./profile'),
  notes: require('./notes'),
  tags: require('./tags'),
  tradingActivities: require('./tradingActivities'),
  tradingAccount: require('./tradingAccount'),
  statistics: require('./statistics'),
  profiles: require('./profiles'),
  upload: require('./upload'),
  leads: require('./leads'),
  files: require('./files'),
  hierarchy: require('./hierarchy'),
  conditionalTags: require('./conditionalTags'),
  rules: require('./rules'),
  clients: require('./clients'),
  callbacks: require('./callbacks'),
  operators: require('./operators'),
  partners: require('./partners'),
  metabase: require('./metabase'),
  filterSet: require('./filterSet'),
};
