module.exports = {
  auth: require('./auth'),
  payment: require('./payment'),
  profile: require('./profile'),
  notes: require('./notes'),
  tags: require('./tags'),
  campaigns: require('./campaigns'),
  games: require('./games'),
  freeSpin: require('./freeSpin'),
  freeSpinTemplate: require('./freeSpinTemplate'),
  rewardPlan: require('./rewardPlan'),
  tradingActivities: require('./tradingActivities'),
  statistics: require('./statistics'),
  profiles: require('./profiles'),
  upload: require('./upload'),
  leads: require('./leads'),
  files: require('./files'),
  hierarchy: require('./hierarchy'),
  conditionalTags: require('./conditionalTags'),
  rules: require('./rules'),
  clients: require('./clients'),
};
