const {
  createUser,
  createBranch,
  getHierarchyUser,
  getHierarchyUsers,
  getHierarchyBranch,
  getCustomersSubtree,
  getLeadsSubtree,
  getOperatorsSubtree,
  getPartnersSubtree,
  getUserBranchHierarchy,
  getUsersByType,
  getBranchHierarchy,
  getBranchHierarchyTree,
  getUsersByBranch,
  getBranchChildren,
  updateUserHierarchy,
  updateBranchHierarchy,
  bulkUpdateHierarchyUser,
  bulkMassAssignHierarchyUser,
  getBrand,
} = require('./hierarchyRequests');

const {
  getHierarchyMappedOperators,
  buildRequestObject,
  multipleRequest,
  getClientBulkUpdateData,
} = require('./hierarchyHelpers');

module.exports = {
  helpers: {
    getHierarchyMappedOperators,
    buildRequestObject,
    multipleRequest,
    getClientBulkUpdateData,
  },
  requests: {
    createUser,
    createBranch,
    getHierarchyUser,
    getHierarchyUsers,
    getHierarchyBranch,
    getCustomersSubtree,
    getLeadsSubtree,
    getOperatorsSubtree,
    getPartnersSubtree,
    getUserBranchHierarchy,
    getUsersByType,
    getBranchHierarchy,
    getBranchHierarchyTree,
    getUsersByBranch,
    getBranchChildren,
    updateUserHierarchy,
    updateBranchHierarchy,
    bulkUpdateHierarchyUser,
    bulkMassAssignHierarchyUser,
    getBrand,
  },
};
