const {
  createUser,
  createBranch,
  getHierarchyUser,
  getHierarchyUsers,
  getHierarchyBranch,
  getCustomersSubtree,
  getLeadsSubtree,
  getOperatorsSubtree,
  getPartnersSubtree,
  getObserverForSubtree,
  checkAccess,
  getUserBranchHierarchy,
  getUsersByType,
  getBranchHierarchy,
  getBranchHierarchyTree,
  getUsersByBranch,
  getBranchChildren,
  bulkUpdateHierarchyUser,
  bulkMassAssignHierarchyUser,
  getBrand,
  updateUserBranches,
  updateHierarchyUser,
} = require('./hierarchyRequests');

const { getHierarchyMappedOperators } = require('./hierarchyHelpers');

module.exports = {
  helpers: {
    getHierarchyMappedOperators,
  },
  requests: {
    createUser,
    createBranch,
    getHierarchyUser,
    getHierarchyUsers,
    getHierarchyBranch,
    getCustomersSubtree,
    getLeadsSubtree,
    getOperatorsSubtree,
    getPartnersSubtree,
    getObserverForSubtree,
    checkAccess,
    getUserBranchHierarchy,
    getUsersByType,
    getBranchHierarchy,
    getBranchHierarchyTree,
    getUsersByBranch,
    getBranchChildren,
    bulkUpdateHierarchyUser,
    bulkMassAssignHierarchyUser,
    getBrand,
    updateUserBranches,
    updateHierarchyUser,
  },
};
